version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:14.3
    container_name: {{app_name}}_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.10
    container_name: {{app_name}}_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5454:80"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: {{app_name}}_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:7
    container_name: {{app_name}}_redis
